### ISSUE TITLE
Father Of SVG

### ISSUE THREAD

**Issue by tobireif** [svgeesus/svgeesus.github.io#1]
Hi Chris!

Just something to consider:

http://svgees.us/
[Chris Lilley is] "Considered “the father of SVG”"

http://www.adobe.com/devnet/svg/articles/svg-jon-ferraiolo-interview.html
"Vincent interviewed Jon Ferraiolo after the "Graphical Web" conference. Jon is often called the father of SVG"

https://www.w3.org/TR/SVG10/
"Editor: Jon Ferraiolo"
and the author list
https://www.w3.org/TR/SVG10/#AuthorList
lists 37 authors, including you.

It seems to me that SVG was created by many people. There was just one editor, so it might make sense to call Jon Ferraiolo the Father Of SVG, but given that so many people worked hard to create SVG 1.0 it doesn't seem fitting to claim a title that doesn't honor all the many other authors and especially doesn't honor the editor of SVG 1.0 .

The web community is forever indebted to all the authors and the editor of SVG 1.0 . Thanks!

Sincerely,
Tobi

**Comment by vhardy** [comment]
For what it is worth, I think Tobi makes a fair point. May be there are multiple father figures, Jon and Chris being clear ones!

**Comment by svgeesus** [comment]
Thanks for the comment, Tobi. SVG was indeed created by very many people (not just those listed as authors). 

The title was in fact not "claimed" as you put it, but awarded to me at the 2008 SVG Open conference in Nuremberg, somewhat by analogy with Jon Bosak being considered the "father of XML" or Hakon Lie and Bert Bos being the fathers of CSS. (In absentia, as I was severely ill at the time and was unable to attend). SVG Open was the precursor to the Graphical Web conference you mentioned.

I think that this was because I wrote the original requirements document (in 1996), called for ideas on a truly Web-like vector graphics language, pushed hard to get the first SVG group chartered in 1998 and convinced organizations who were fiercely competitive to work together for the common good. I also chaired the SVG WG for the first eight years of it's existence. I guess the title reflected that long service.

Jon of course did a fantastic job as editor for SVG 1 and also internally at Adobe to drive implementation and adoption of SVG in their products. 

Vincent by the way (first at Sun and then at Adobe) was also instrumental in pushing SVG forward.

**Comment by tobireif** [comment]
My intent sincerely never was to belittle your fundamental and numerous and significant achievements and contributions!

But Jon lists these contributions:

"You are often referred to as the spiritual father of SVG. Can you tell us what role you played in the inception of that key Web technology?"

"Before the SVG activity began at the World Wide Web Consortium, I was the primary author of the PGML submission (Precision Graphics Markup Language) which served as the starting point for the SVG language. Once the  SVG Working Group started up in August 1998, as sole editor of the SVG Specification, I edited every word in the SVG 1.0 specification. I was deeply involved in nearly all technical discussions in defining the SVG language and probably wrote the majority of the text and examples in the specification. On the Adobe side, I served as architect for Adobe's SVG-related product activities, including working with the Adobe SVG Viewer team. I wrote the original save-as-PGML code in Adobe Illustrator (which evolved into Illustrator's save-as-SVG feature)."

The issue I see is that the title "**The** Father of SVG" (eg as on http://svgees.us/ ) can only be carried by one single person (whether awarded or perpetuated), and thus excludes several other main creators. A title such as  "A Major Creator of SVG" would not exclude any of the other creators (but there might be better sounding options 😀).

I do not think it's 100% OK (or necessary) to award the title "The Father of SVG" to anyone (or to perpetuate it), for the reason above.
Instead it's sensible, feasible, and completely OK to honor any given creator/contributor for the respective concrete achievements/contributions. Listing one's own achievements/contributions (eg as you did above) also is perfectly fine in my opinion, including eg on one's own website.

I myself would not perpetuate a title awarded to me if it excludes several other major creators of that same technology.

But all this is just food for thought, I'm not the title police 😀

> SVG Open was the precursor to the Graphical Web conference you mentioned.

Yes, I was (we both were) at the first SVG Open conference 😀
